# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile_available_spas.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobile_available_spas.proto',
  package='com.levven.protobuf',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bmobile_available_spas.proto\x12\x13\x63om.levven.protobuf\"\xe0\x01\n\x15mobile_available_spas\x12H\n\tmobileSpa\x18\x01 \x03(\x0b\x32\x35.com.levven.protobuf.mobile_available_spas.mobile_spa\x1a}\n\nmobile_spa\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x15\n\rpackProductId\x18\x02 \x01(\t\x12\x13\n\x0bproductCode\x18\x03 \x01(\x05\x12\x10\n\x08nickName\x18\x04 \x01(\t\x12\x11\n\tconnected\x18\x05 \x01(\x08\x12\x10\n\x08serverId\x18\x06 \x01(\t'
)




_MOBILE_AVAILABLE_SPAS_MOBILE_SPA = _descriptor.Descriptor(
  name='mobile_spa',
  full_name='com.levven.protobuf.mobile_available_spas.mobile_spa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packProductId', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.packProductId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='productCode', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.productCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickName', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.nickName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.connected', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='com.levven.protobuf.mobile_available_spas.mobile_spa.serverId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=277,
)

_MOBILE_AVAILABLE_SPAS = _descriptor.Descriptor(
  name='mobile_available_spas',
  full_name='com.levven.protobuf.mobile_available_spas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobileSpa', full_name='com.levven.protobuf.mobile_available_spas.mobileSpa', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MOBILE_AVAILABLE_SPAS_MOBILE_SPA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=277,
)

_MOBILE_AVAILABLE_SPAS_MOBILE_SPA.containing_type = _MOBILE_AVAILABLE_SPAS
_MOBILE_AVAILABLE_SPAS.fields_by_name['mobileSpa'].message_type = _MOBILE_AVAILABLE_SPAS_MOBILE_SPA
DESCRIPTOR.message_types_by_name['mobile_available_spas'] = _MOBILE_AVAILABLE_SPAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mobile_available_spas = _reflection.GeneratedProtocolMessageType('mobile_available_spas', (_message.Message,), {

  'mobile_spa' : _reflection.GeneratedProtocolMessageType('mobile_spa', (_message.Message,), {
    'DESCRIPTOR' : _MOBILE_AVAILABLE_SPAS_MOBILE_SPA,
    '__module__' : 'mobile_available_spas_pb2'
    # @@protoc_insertion_point(class_scope:com.levven.protobuf.mobile_available_spas.mobile_spa)
    })
  ,
  'DESCRIPTOR' : _MOBILE_AVAILABLE_SPAS,
  '__module__' : 'mobile_available_spas_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.mobile_available_spas)
  })
_sym_db.RegisterMessage(mobile_available_spas)
_sym_db.RegisterMessage(mobile_available_spas.mobile_spa)


# @@protoc_insertion_point(module_scope)
