# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MobileAuthenticate.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MobileAuthenticate.proto',
  package='com.levven.protobuf',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18MobileAuthenticate.proto\x12\x13\x63om.levven.protobuf\"\x82\x01\n\x13mobile_authenticate\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04salt\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12=\n\x0b\x61uth_status\x18\x04 \x01(\x0e\x32(.com.levven.protobuf.AUTHENTICATE_STATUS*I\n\x13\x41UTHENTICATE_STATUS\x12\x18\n\x14\x41UTHENTICATE_SUCCESS\x10\x00\x12\x18\n\x14\x41UTHENTICATE_FAILURE\x10\x01'
)

_AUTHENTICATE_STATUS = _descriptor.EnumDescriptor(
  name='AUTHENTICATE_STATUS',
  full_name='com.levven.protobuf.AUTHENTICATE_STATUS',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHENTICATE_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=182,
  serialized_end=255,
)
_sym_db.RegisterEnumDescriptor(_AUTHENTICATE_STATUS)

AUTHENTICATE_STATUS = enum_type_wrapper.EnumTypeWrapper(_AUTHENTICATE_STATUS)
AUTHENTICATE_SUCCESS = 0
AUTHENTICATE_FAILURE = 1



_MOBILE_AUTHENTICATE = _descriptor.Descriptor(
  name='mobile_authenticate',
  full_name='com.levven.protobuf.mobile_authenticate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='com.levven.protobuf.mobile_authenticate.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salt', full_name='com.levven.protobuf.mobile_authenticate.salt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='com.levven.protobuf.mobile_authenticate.hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_status', full_name='com.levven.protobuf.mobile_authenticate.auth_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=180,
)

_MOBILE_AUTHENTICATE.fields_by_name['auth_status'].enum_type = _AUTHENTICATE_STATUS
DESCRIPTOR.message_types_by_name['mobile_authenticate'] = _MOBILE_AUTHENTICATE
DESCRIPTOR.enum_types_by_name['AUTHENTICATE_STATUS'] = _AUTHENTICATE_STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mobile_authenticate = _reflection.GeneratedProtocolMessageType('mobile_authenticate', (_message.Message,), {
  'DESCRIPTOR' : _MOBILE_AUTHENTICATE,
  '__module__' : 'MobileAuthenticate_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.mobile_authenticate)
  })
_sym_db.RegisterMessage(mobile_authenticate)


# @@protoc_insertion_point(module_scope)
