# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile_spa_registration.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobile_spa_registration.proto',
  package='com.levven.protobuf',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dmobile_spa_registration.proto\x12\x13\x63om.levven.protobuf\"\x9f\x01\n\x17mobile_spa_registration\x12\x19\n\x11registration_code\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x14\n\x0cspa_nickname\x18\x03 \x01(\t\x12<\n\nreg_status\x18\x04 \x01(\x0e\x32(.com.levven.protobuf.REGISTRATION_STATUS*I\n\x13REGISTRATION_STATUS\x12\x18\n\x14REGISTRATION_SUCCESS\x10\x00\x12\x18\n\x14REGISTRATION_FAILURE\x10\x01'
)

_REGISTRATION_STATUS = _descriptor.EnumDescriptor(
  name='REGISTRATION_STATUS',
  full_name='com.levven.protobuf.REGISTRATION_STATUS',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REGISTRATION_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=216,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_REGISTRATION_STATUS)

REGISTRATION_STATUS = enum_type_wrapper.EnumTypeWrapper(_REGISTRATION_STATUS)
REGISTRATION_SUCCESS = 0
REGISTRATION_FAILURE = 1



_MOBILE_SPA_REGISTRATION = _descriptor.Descriptor(
  name='mobile_spa_registration',
  full_name='com.levven.protobuf.mobile_spa_registration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_code', full_name='com.levven.protobuf.mobile_spa_registration.registration_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='com.levven.protobuf.mobile_spa_registration.serial_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_nickname', full_name='com.levven.protobuf.mobile_spa_registration.spa_nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_status', full_name='com.levven.protobuf.mobile_spa_registration.reg_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=214,
)

_MOBILE_SPA_REGISTRATION.fields_by_name['reg_status'].enum_type = _REGISTRATION_STATUS
DESCRIPTOR.message_types_by_name['mobile_spa_registration'] = _MOBILE_SPA_REGISTRATION
DESCRIPTOR.enum_types_by_name['REGISTRATION_STATUS'] = _REGISTRATION_STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mobile_spa_registration = _reflection.GeneratedProtocolMessageType('mobile_spa_registration', (_message.Message,), {
  'DESCRIPTOR' : _MOBILE_SPA_REGISTRATION,
  '__module__' : 'mobile_spa_registration_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.mobile_spa_registration)
  })
_sym_db.RegisterMessage(mobile_spa_registration)


# @@protoc_insertion_point(module_scope)
