# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spa_settings.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spa_settings.proto',
  package='com.levven.protobuf.coldfire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12spa_settings.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xc2\x05\n\x0cspa_settings\x12 \n\x18max_filtration_frequency\x18\x01 \x01(\x05\x12 \n\x18min_filtration_frequency\x18\x02 \x01(\x05\x12\x1c\n\x14\x66iltration_frequency\x18\x03 \x01(\x05\x12\x1f\n\x17max_filtration_duration\x18\x04 \x01(\x05\x12\x1f\n\x17min_filtration_duration\x18\x05 \x01(\x05\x12\x1b\n\x13\x66iltration_duration\x18\x06 \x01(\x05\x12\x17\n\x0fmax_onzen_hours\x18\x07 \x01(\x05\x12\x17\n\x0fmin_onzen_hours\x18\x08 \x01(\x05\x12\x13\n\x0bonzen_hours\x18\t \x01(\x05\x12\x18\n\x10max_onzen_cycles\x18\n \x01(\x05\x12\x18\n\x10min_onzen_cycles\x18\x0b \x01(\x05\x12\x14\n\x0conzen_cycles\x18\x0c \x01(\x05\x12\x17\n\x0fmax_ozone_hours\x18\r \x01(\x05\x12\x17\n\x0fmin_ozone_hours\x18\x0e \x01(\x05\x12\x13\n\x0bozone_hours\x18\x0f \x01(\x05\x12\x18\n\x10max_ozone_cycles\x18\x10 \x01(\x05\x12\x18\n\x10min_ozone_cycles\x18\x11 \x01(\x05\x12\x14\n\x0cozone_cycles\x18\x12 \x01(\x05\x12\x19\n\x11\x66ilter_suspension\x18\x13 \x01(\x08\x12\x1d\n\x15\x66lash_lights_on_error\x18\x14 \x01(\x08\x12\x1a\n\x12temperature_offset\x18\x15 \x01(\x05\x12\x16\n\x0esauna_duration\x18\x16 \x01(\x05\x12\x17\n\x0fmin_temperature\x18\x17 \x01(\x05\x12\x17\n\x0fmax_temperature\x18\x18 \x01(\x05\x12\x19\n\x11\x66iltration_offset\x18\x19 \x01(\x05\x12\x14\n\x0cspaboy_hours\x18\x1a \x01(\x05'
)




_SPA_SETTINGS = _descriptor.Descriptor(
  name='spa_settings',
  full_name='com.levven.protobuf.coldfire.spa_settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_filtration_frequency', full_name='com.levven.protobuf.coldfire.spa_settings.max_filtration_frequency', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_filtration_frequency', full_name='com.levven.protobuf.coldfire.spa_settings.min_filtration_frequency', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filtration_frequency', full_name='com.levven.protobuf.coldfire.spa_settings.filtration_frequency', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_filtration_duration', full_name='com.levven.protobuf.coldfire.spa_settings.max_filtration_duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_filtration_duration', full_name='com.levven.protobuf.coldfire.spa_settings.min_filtration_duration', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filtration_duration', full_name='com.levven.protobuf.coldfire.spa_settings.filtration_duration', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_onzen_hours', full_name='com.levven.protobuf.coldfire.spa_settings.max_onzen_hours', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_onzen_hours', full_name='com.levven.protobuf.coldfire.spa_settings.min_onzen_hours', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onzen_hours', full_name='com.levven.protobuf.coldfire.spa_settings.onzen_hours', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_onzen_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.max_onzen_cycles', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_onzen_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.min_onzen_cycles', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onzen_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.onzen_cycles', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_ozone_hours', full_name='com.levven.protobuf.coldfire.spa_settings.max_ozone_hours', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_ozone_hours', full_name='com.levven.protobuf.coldfire.spa_settings.min_ozone_hours', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ozone_hours', full_name='com.levven.protobuf.coldfire.spa_settings.ozone_hours', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_ozone_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.max_ozone_cycles', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_ozone_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.min_ozone_cycles', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ozone_cycles', full_name='com.levven.protobuf.coldfire.spa_settings.ozone_cycles', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_suspension', full_name='com.levven.protobuf.coldfire.spa_settings.filter_suspension', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flash_lights_on_error', full_name='com.levven.protobuf.coldfire.spa_settings.flash_lights_on_error', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature_offset', full_name='com.levven.protobuf.coldfire.spa_settings.temperature_offset', index=20,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sauna_duration', full_name='com.levven.protobuf.coldfire.spa_settings.sauna_duration', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_temperature', full_name='com.levven.protobuf.coldfire.spa_settings.min_temperature', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_temperature', full_name='com.levven.protobuf.coldfire.spa_settings.max_temperature', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filtration_offset', full_name='com.levven.protobuf.coldfire.spa_settings.filtration_offset', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spaboy_hours', full_name='com.levven.protobuf.coldfire.spa_settings.spaboy_hours', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=759,
)

DESCRIPTOR.message_types_by_name['spa_settings'] = _SPA_SETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_settings = _reflection.GeneratedProtocolMessageType('spa_settings', (_message.Message,), {
  'DESCRIPTOR' : _SPA_SETTINGS,
  '__module__' : 'spa_settings_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.coldfire.spa_settings)
  })
_sym_db.RegisterMessage(spa_settings)


# @@protoc_insertion_point(module_scope)
