# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spa_configuration.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spa_configuration.proto',
  package='SpaServer.protobuf.ColdFire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17spa_configuration.proto\x12\x1bSpaServer.protobuf.ColdFire\"\x9e\x03\n\x11spa_configuration\x12\x0e\n\x06pump_1\x18\x01 \x01(\x08\x12\x0e\n\x06pump_2\x18\x02 \x01(\x08\x12\x0e\n\x06pump_3\x18\x03 \x01(\x08\x12\x0e\n\x06pump_4\x18\x04 \x01(\x08\x12\x0e\n\x06pump_5\x18\x05 \x01(\x08\x12\x10\n\x08\x62lower_1\x18\x06 \x01(\x08\x12\x10\n\x08\x62lower_2\x18\x07 \x01(\x08\x12\x0e\n\x06lights\x18\x08 \x01(\x08\x12\x0e\n\x06stereo\x18\t \x01(\x08\x12\x10\n\x08heater_1\x18\n \x01(\x08\x12\x10\n\x08heater_2\x18\x0b \x01(\x08\x12\x0e\n\x06\x66ilter\x18\x0c \x01(\x08\x12\r\n\x05onzen\x18\r \x01(\x08\x12\x14\n\x0cozone_peak_1\x18\x0e \x01(\x08\x12\x14\n\x0cozone_peak_2\x18\x0f \x01(\x08\x12\x13\n\x0b\x65xhaust_fan\x18\x10 \x01(\x08\x12\x36\n\npowerlines\x18\x11 \x01(\x0e\x32\".SpaServer.protobuf.ColdFire.PHASE\x12\x14\n\x0c\x62reaker_size\x18\x12 \x01(\x05\x12\x13\n\x0bsmart_onzen\x18\x13 \x01(\x05\x12\x0e\n\x06\x66ogger\x18\x14 \x01(\x08*7\n\x05PHASE\x12\x0e\n\nTRUE_THREE\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03'
)

_PHASE = _descriptor.EnumDescriptor(
  name='PHASE',
  full_name='SpaServer.protobuf.ColdFire.PHASE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRUE_THREE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THREE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=473,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_PHASE)

PHASE = enum_type_wrapper.EnumTypeWrapper(_PHASE)
TRUE_THREE = 0
SINGLE = 1
TWO = 2
THREE = 3



_SPA_CONFIGURATION = _descriptor.Descriptor(
  name='spa_configuration',
  full_name='SpaServer.protobuf.ColdFire.spa_configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pump_1', full_name='SpaServer.protobuf.ColdFire.spa_configuration.pump_1', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump_2', full_name='SpaServer.protobuf.ColdFire.spa_configuration.pump_2', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump_3', full_name='SpaServer.protobuf.ColdFire.spa_configuration.pump_3', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump_4', full_name='SpaServer.protobuf.ColdFire.spa_configuration.pump_4', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pump_5', full_name='SpaServer.protobuf.ColdFire.spa_configuration.pump_5', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blower_1', full_name='SpaServer.protobuf.ColdFire.spa_configuration.blower_1', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blower_2', full_name='SpaServer.protobuf.ColdFire.spa_configuration.blower_2', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lights', full_name='SpaServer.protobuf.ColdFire.spa_configuration.lights', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stereo', full_name='SpaServer.protobuf.ColdFire.spa_configuration.stereo', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heater_1', full_name='SpaServer.protobuf.ColdFire.spa_configuration.heater_1', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heater_2', full_name='SpaServer.protobuf.ColdFire.spa_configuration.heater_2', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter', full_name='SpaServer.protobuf.ColdFire.spa_configuration.filter', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onzen', full_name='SpaServer.protobuf.ColdFire.spa_configuration.onzen', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ozone_peak_1', full_name='SpaServer.protobuf.ColdFire.spa_configuration.ozone_peak_1', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ozone_peak_2', full_name='SpaServer.protobuf.ColdFire.spa_configuration.ozone_peak_2', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exhaust_fan', full_name='SpaServer.protobuf.ColdFire.spa_configuration.exhaust_fan', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powerlines', full_name='SpaServer.protobuf.ColdFire.spa_configuration.powerlines', index=16,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='breaker_size', full_name='SpaServer.protobuf.ColdFire.spa_configuration.breaker_size', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smart_onzen', full_name='SpaServer.protobuf.ColdFire.spa_configuration.smart_onzen', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fogger', full_name='SpaServer.protobuf.ColdFire.spa_configuration.fogger', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=471,
)

_SPA_CONFIGURATION.fields_by_name['powerlines'].enum_type = _PHASE
DESCRIPTOR.message_types_by_name['spa_configuration'] = _SPA_CONFIGURATION
DESCRIPTOR.enum_types_by_name['PHASE'] = _PHASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_configuration = _reflection.GeneratedProtocolMessageType('spa_configuration', (_message.Message,), {
  'DESCRIPTOR' : _SPA_CONFIGURATION,
  '__module__' : 'spa_configuration_pb2'
  # @@protoc_insertion_point(class_scope:SpaServer.protobuf.ColdFire.spa_configuration)
  })
_sym_db.RegisterMessage(spa_configuration)


# @@protoc_insertion_point(module_scope)
