# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaCommand.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaCommand.proto',
  package='spa',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10SpaCommand.proto\x12\x03spa\"\x9c\x05\n\x0bspa_command\x12+\n#set_temperature_setpoint_fahrenheit\x18\x01 \x01(\x05\x12(\n\nset_pump_1\x18\x02 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_2\x18\x03 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_3\x18\x04 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_4\x18\x05 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_5\x18\x06 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12*\n\x0cset_blower_1\x18\x07 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12*\n\x0cset_blower_2\x18\x08 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12\x12\n\nset_lights\x18\t \x01(\x08\x12\x12\n\nset_stereo\x18\n \x01(\x08\x12\x12\n\nset_filter\x18\x0b \x01(\x08\x12\x11\n\tset_onzen\x18\x0c \x01(\x08\x12\x11\n\tset_ozone\x18\r \x01(\x08\x12\x17\n\x0fset_exhaust_fan\x18\x0e \x01(\x08\x12-\n\x0fset_sauna_state\x18\x0f \x01(\x0e\x32\x14.spa.SET_SAUNA_STATE\x12\x1b\n\x13set_sauna_time_left\x18\x10 \x01(\x05\x12\x0e\n\x06\x61ll_on\x18\x11 \x01(\x08\x12\x12\n\nset_fogger\x18\x12 \x01(\x08\x12\x14\n\x0cspaboy_boost\x18\x13 \x01(\x08\x12\x19\n\x11set_orp_level_low\x18\x32 \x01(\x05\x12\x1a\n\x12set_orp_level_high\x18\x33 \x01(\x05*-\n\x0fSET_PUMP_STATUS\x12\x07\n\x03OFF\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02*P\n\x0fSET_SAUNA_STATE\x12\x08\n\x04IDLE\x10\x00\x12\t\n\x05TIMER\x10\x01\x12\x0c\n\x08PRESET_A\x10\x02\x12\x0c\n\x08PRESET_B\x10\x03\x12\x0c\n\x08PRESET_C\x10\x04'
)

_SET_PUMP_STATUS = _descriptor.EnumDescriptor(
  name='SET_PUMP_STATUS',
  full_name='spa.SET_PUMP_STATUS',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=696,
  serialized_end=741,
)
_sym_db.RegisterEnumDescriptor(_SET_PUMP_STATUS)

SET_PUMP_STATUS = enum_type_wrapper.EnumTypeWrapper(_SET_PUMP_STATUS)
_SET_SAUNA_STATE = _descriptor.EnumDescriptor(
  name='SET_SAUNA_STATE',
  full_name='spa.SET_SAUNA_STATE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRESET_A', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRESET_B', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRESET_C', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=743,
  serialized_end=823,
)
_sym_db.RegisterEnumDescriptor(_SET_SAUNA_STATE)

SET_SAUNA_STATE = enum_type_wrapper.EnumTypeWrapper(_SET_SAUNA_STATE)
OFF = 0
LOW = 1
HIGH = 2
IDLE = 0
TIMER = 1
PRESET_A = 2
PRESET_B = 3
PRESET_C = 4



_SPA_COMMAND = _descriptor.Descriptor(
  name='spa_command',
  full_name='spa.spa_command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_temperature_setpoint_fahrenheit', full_name='spa.spa_command.set_temperature_setpoint_fahrenheit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_1', full_name='spa.spa_command.set_pump_1', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_2', full_name='spa.spa_command.set_pump_2', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_3', full_name='spa.spa_command.set_pump_3', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_4', full_name='spa.spa_command.set_pump_4', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_pump_5', full_name='spa.spa_command.set_pump_5', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_blower_1', full_name='spa.spa_command.set_blower_1', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_blower_2', full_name='spa.spa_command.set_blower_2', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_lights', full_name='spa.spa_command.set_lights', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_stereo', full_name='spa.spa_command.set_stereo', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_filter', full_name='spa.spa_command.set_filter', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_onzen', full_name='spa.spa_command.set_onzen', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_ozone', full_name='spa.spa_command.set_ozone', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_exhaust_fan', full_name='spa.spa_command.set_exhaust_fan', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_sauna_state', full_name='spa.spa_command.set_sauna_state', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_sauna_time_left', full_name='spa.spa_command.set_sauna_time_left', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_on', full_name='spa.spa_command.all_on', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_fogger', full_name='spa.spa_command.set_fogger', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spaboy_boost', full_name='spa.spa_command.spaboy_boost', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_orp_level_low', full_name='spa.spa_command.set_orp_level_low', index=19,
      number=50, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_orp_level_high', full_name='spa.spa_command.set_orp_level_high', index=20,
      number=51, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=694,
)

_SPA_COMMAND.fields_by_name['set_pump_1'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_pump_2'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_pump_3'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_pump_4'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_pump_5'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_blower_1'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_blower_2'].enum_type = _SET_PUMP_STATUS
_SPA_COMMAND.fields_by_name['set_sauna_state'].enum_type = _SET_SAUNA_STATE
DESCRIPTOR.message_types_by_name['spa_command'] = _SPA_COMMAND
DESCRIPTOR.enum_types_by_name['SET_PUMP_STATUS'] = _SET_PUMP_STATUS
DESCRIPTOR.enum_types_by_name['SET_SAUNA_STATE'] = _SET_SAUNA_STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_command = _reflection.GeneratedProtocolMessageType('spa_command', (_message.Message,), {
  'DESCRIPTOR' : _SPA_COMMAND,
  '__module__' : 'SpaCommand_pb2'
  # @@protoc_insertion_point(class_scope:spa.spa_command)
  })
_sym_db.RegisterMessage(spa_command)


# @@protoc_insertion_point(module_scope)
