# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaError.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaError.proto',
  package='com.levven.protobuf.coldfire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eSpaError.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\x83\x02\n\tspa_error\x12\x0f\n\x07no_flow\x18\x01 \x01(\x08\x12\x13\n\x0b\x66low_switch\x18\x02 \x01(\x08\x12\x1f\n\x17heater_over_temperature\x18\x03 \x01(\x08\x12\x1c\n\x14spa_over_temperature\x18\x04 \x01(\x08\x12\x1d\n\x15spa_temperature_probe\x18\x05 \x01(\x08\x12\x16\n\x0espa_high_limit\x18\x06 \x01(\x08\x12\x0e\n\x06\x65\x65prom\x18\x07 \x01(\x08\x12\x16\n\x0e\x66reeze_protect\x18\x08 \x01(\x08\x12\x0f\n\x07ph_high\x18\t \x01(\x08\x12!\n\x19heater_probe_disconnected\x18\n \x01(\x08'
)




_SPA_ERROR = _descriptor.Descriptor(
  name='spa_error',
  full_name='com.levven.protobuf.coldfire.spa_error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='no_flow', full_name='com.levven.protobuf.coldfire.spa_error.no_flow', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flow_switch', full_name='com.levven.protobuf.coldfire.spa_error.flow_switch', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heater_over_temperature', full_name='com.levven.protobuf.coldfire.spa_error.heater_over_temperature', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_over_temperature', full_name='com.levven.protobuf.coldfire.spa_error.spa_over_temperature', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_temperature_probe', full_name='com.levven.protobuf.coldfire.spa_error.spa_temperature_probe', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_high_limit', full_name='com.levven.protobuf.coldfire.spa_error.spa_high_limit', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eeprom', full_name='com.levven.protobuf.coldfire.spa_error.eeprom', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freeze_protect', full_name='com.levven.protobuf.coldfire.spa_error.freeze_protect', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ph_high', full_name='com.levven.protobuf.coldfire.spa_error.ph_high', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heater_probe_disconnected', full_name='com.levven.protobuf.coldfire.spa_error.heater_probe_disconnected', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=308,
)

DESCRIPTOR.message_types_by_name['spa_error'] = _SPA_ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_error = _reflection.GeneratedProtocolMessageType('spa_error', (_message.Message,), {
  'DESCRIPTOR' : _SPA_ERROR,
  '__module__' : 'SpaError_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.coldfire.spa_error)
  })
_sym_db.RegisterMessage(spa_error)


# @@protoc_insertion_point(module_scope)
