# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaInformation.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaInformation.proto',
  package='com.levven.protobuf.coldfire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14SpaInformation.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xaa\x03\n\x0fspa_information\x12\x1a\n\x12pack_serial_number\x18\x01 \x01(\t\x12\x1d\n\x15pack_firmware_version\x18\x02 \x01(\t\x12\x1d\n\x15pack_hardware_version\x18\x03 \x01(\t\x12\x17\n\x0fpack_product_id\x18\x04 \x01(\t\x12\x15\n\rpack_board_id\x18\x05 \x01(\t\x12\x1a\n\x12topside_product_id\x18\x06 \x01(\t\x12 \n\x18topside_software_version\x18\x07 \x01(\t\x12\x0c\n\x04guid\x18\x08 \x01(\t\x12\x38\n\x08spa_type\x18\t \x01(\x0e\x32&.com.levven.protobuf.coldfire.SPA_TYPE\x12\x1c\n\x14website_registration\x18\n \x01(\x08\x12$\n\x1cwebsite_registration_confirm\x18\x0b \x01(\x08\x12\x13\n\x0bmac_address\x18\x0c \x01(\x0c\x12\x18\n\x10\x66irmware_version\x18\r \x01(\r\x12\x14\n\x0cproduct_code\x18\x0e \x01(\r*0\n\x08SPA_TYPE\x12\x0b\n\x07HOT_TUB\x10\x00\x12\x0c\n\x08\x43OLD_TUB\x10\x01\x12\t\n\x05SAUNA\x10\x02*\x85\x02\n\x0cPRODUCT_CODE\x12\x15\n\x0fSPA_NA_COLDFIRE\x10\x80\x80\x04\x12\x17\n\x11SPA_EURO_COLDFIRE\x10\x81\x80\x04\x12\x10\n\nSPA_NA_LPC\x10\x82\x80\x04\x12\x12\n\x0cSPA_EURO_LPC\x10\x83\x80\x04\x12\x14\n\x0eSAUNA_COLDFIRE\x10\x80\x80\x08\x12\x0f\n\tSAUNA_LPC\x10\x81\x80\x08\x12\x17\n\x11\x43OLD_TUB_COLDFIRE\x10\x80\x80\x0c\x12\x12\n\x0c\x43OLD_TUB_LPC\x10\x81\x80\x0c\x12\x14\n\x0ePERIPHERAL_WAU\x10\x80\x80\x10\x12\x16\n\x10PERIPHERAL_ONZEN\x10\x81\x80\x10\x12\x1d\n\x17PERIPHERAL_TOP_SIDE_A10\x10\x82\x80\x10'
)

_SPA_TYPE = _descriptor.EnumDescriptor(
  name='SPA_TYPE',
  full_name='com.levven.protobuf.coldfire.SPA_TYPE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOT_TUB', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLD_TUB', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=483,
  serialized_end=531,
)
_sym_db.RegisterEnumDescriptor(_SPA_TYPE)

SPA_TYPE = enum_type_wrapper.EnumTypeWrapper(_SPA_TYPE)
_PRODUCT_CODE = _descriptor.EnumDescriptor(
  name='PRODUCT_CODE',
  full_name='com.levven.protobuf.coldfire.PRODUCT_CODE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPA_NA_COLDFIRE', index=0, number=65536,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPA_EURO_COLDFIRE', index=1, number=65537,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPA_NA_LPC', index=2, number=65538,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPA_EURO_LPC', index=3, number=65539,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_COLDFIRE', index=4, number=131072,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAUNA_LPC', index=5, number=131073,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLD_TUB_COLDFIRE', index=6, number=196608,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COLD_TUB_LPC', index=7, number=196609,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_WAU', index=8, number=262144,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_ONZEN', index=9, number=262145,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_TOP_SIDE_A10', index=10, number=262146,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=534,
  serialized_end=795,
)
_sym_db.RegisterEnumDescriptor(_PRODUCT_CODE)

PRODUCT_CODE = enum_type_wrapper.EnumTypeWrapper(_PRODUCT_CODE)
HOT_TUB = 0
COLD_TUB = 1
SAUNA = 2
SPA_NA_COLDFIRE = 65536
SPA_EURO_COLDFIRE = 65537
SPA_NA_LPC = 65538
SPA_EURO_LPC = 65539
SAUNA_COLDFIRE = 131072
SAUNA_LPC = 131073
COLD_TUB_COLDFIRE = 196608
COLD_TUB_LPC = 196609
PERIPHERAL_WAU = 262144
PERIPHERAL_ONZEN = 262145
PERIPHERAL_TOP_SIDE_A10 = 262146



_SPA_INFORMATION = _descriptor.Descriptor(
  name='spa_information',
  full_name='com.levven.protobuf.coldfire.spa_information',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pack_serial_number', full_name='com.levven.protobuf.coldfire.spa_information.pack_serial_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pack_firmware_version', full_name='com.levven.protobuf.coldfire.spa_information.pack_firmware_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pack_hardware_version', full_name='com.levven.protobuf.coldfire.spa_information.pack_hardware_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pack_product_id', full_name='com.levven.protobuf.coldfire.spa_information.pack_product_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pack_board_id', full_name='com.levven.protobuf.coldfire.spa_information.pack_board_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topside_product_id', full_name='com.levven.protobuf.coldfire.spa_information.topside_product_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topside_software_version', full_name='com.levven.protobuf.coldfire.spa_information.topside_software_version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guid', full_name='com.levven.protobuf.coldfire.spa_information.guid', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spa_type', full_name='com.levven.protobuf.coldfire.spa_information.spa_type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='website_registration', full_name='com.levven.protobuf.coldfire.spa_information.website_registration', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='website_registration_confirm', full_name='com.levven.protobuf.coldfire.spa_information.website_registration_confirm', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mac_address', full_name='com.levven.protobuf.coldfire.spa_information.mac_address', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firmware_version', full_name='com.levven.protobuf.coldfire.spa_information.firmware_version', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_code', full_name='com.levven.protobuf.coldfire.spa_information.product_code', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=481,
)

_SPA_INFORMATION.fields_by_name['spa_type'].enum_type = _SPA_TYPE
DESCRIPTOR.message_types_by_name['spa_information'] = _SPA_INFORMATION
DESCRIPTOR.enum_types_by_name['SPA_TYPE'] = _SPA_TYPE
DESCRIPTOR.enum_types_by_name['PRODUCT_CODE'] = _PRODUCT_CODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_information = _reflection.GeneratedProtocolMessageType('spa_information', (_message.Message,), {
  'DESCRIPTOR' : _SPA_INFORMATION,
  '__module__' : 'SpaInformation_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.coldfire.spa_information)
  })
_sym_db.RegisterMessage(spa_information)


# @@protoc_insertion_point(module_scope)
