# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaOnzen.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaOnzen.proto',
  package='spa',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eSpaOnzen.proto\x12\x03spa\"S\n\x12spa_onzen_settings\x12\x1a\n\x12pack_serial_number\x18\x01 \x01(\t\x12\x0f\n\x07orp_low\x18\x06 \x01(\x05\x12\x10\n\x08orp_high\x18\x07 \x01(\x05'
)




_SPA_ONZEN_SETTINGS = _descriptor.Descriptor(
  name='spa_onzen_settings',
  full_name='spa.spa_onzen_settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pack_serial_number', full_name='spa.spa_onzen_settings.pack_serial_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orp_low', full_name='spa.spa_onzen_settings.orp_low', index=1,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orp_high', full_name='spa.spa_onzen_settings.orp_high', index=2,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['spa_onzen_settings'] = _SPA_ONZEN_SETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_onzen_settings = _reflection.GeneratedProtocolMessageType('spa_onzen_settings', (_message.Message,), {
  'DESCRIPTOR' : _SPA_ONZEN_SETTINGS,
  '__module__' : 'SpaOnzen_pb2'
  # @@protoc_insertion_point(class_scope:spa.spa_onzen_settings)
  })
_sym_db.RegisterMessage(spa_onzen_settings)


# @@protoc_insertion_point(module_scope)
