# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaPeak.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaPeak.proto',
  package='com.levven.protobuf.coldfire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rSpaPeak.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xe7\x03\n\x08spa_peak\x12\x0f\n\x07PeakNum\x18\x01 \x01(\x05\x12\x12\n\nPeakStart1\x18\x02 \x01(\x05\x12\x10\n\x08PeakEnd1\x18\x03 \x01(\x05\x12\x12\n\nPeakStart2\x18\x04 \x01(\x05\x12\x10\n\x08PeakEnd2\x18\x05 \x01(\x05\x12\x12\n\nMidPeakNum\x18\x06 \x01(\x05\x12\x15\n\rMidPeakStart1\x18\x07 \x01(\x05\x12\x13\n\x0bMidPeakEnd1\x18\x08 \x01(\x05\x12\x15\n\rMidPeakStart2\x18\t \x01(\x05\x12\x13\n\x0bMidPeakEnd2\x18\n \x01(\x05\x12\x14\n\x0cOffPeakStart\x18\x0b \x01(\x05\x12\x12\n\nOffPeakEnd\x18\x0c \x01(\x05\x12\x0e\n\x06Offset\x18\r \x01(\x05\x12\x12\n\nPeakHeater\x18\x0e \x01(\x08\x12\x12\n\nPeakFilter\x18\x0f \x01(\x08\x12\x11\n\tPeakOzone\x18\x10 \x01(\x08\x12\x15\n\rMidPeakHeater\x18\x11 \x01(\x08\x12\x15\n\rMidPeakFilter\x18\x12 \x01(\x08\x12\x14\n\x0cMidPeakOzone\x18\x13 \x01(\x08\x12\x0b\n\x03Sat\x18\x14 \x01(\x08\x12\x0b\n\x03Sun\x18\x15 \x01(\x08\x12\x0b\n\x03Mon\x18\x16 \x01(\x08\x12\x0b\n\x03Tue\x18\x17 \x01(\x08\x12\x0b\n\x03Wed\x18\x18 \x01(\x08\x12\x0b\n\x03Thu\x18\x19 \x01(\x08\x12\x0b\n\x03\x46ri\x18\x1a \x01(\x08'
)




_SPA_PEAK = _descriptor.Descriptor(
  name='spa_peak',
  full_name='com.levven.protobuf.coldfire.spa_peak',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PeakNum', full_name='com.levven.protobuf.coldfire.spa_peak.PeakNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakStart1', full_name='com.levven.protobuf.coldfire.spa_peak.PeakStart1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakEnd1', full_name='com.levven.protobuf.coldfire.spa_peak.PeakEnd1', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakStart2', full_name='com.levven.protobuf.coldfire.spa_peak.PeakStart2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakEnd2', full_name='com.levven.protobuf.coldfire.spa_peak.PeakEnd2', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakNum', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakNum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakStart1', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakStart1', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakEnd1', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakEnd1', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakStart2', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakStart2', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakEnd2', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakEnd2', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OffPeakStart', full_name='com.levven.protobuf.coldfire.spa_peak.OffPeakStart', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OffPeakEnd', full_name='com.levven.protobuf.coldfire.spa_peak.OffPeakEnd', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Offset', full_name='com.levven.protobuf.coldfire.spa_peak.Offset', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakHeater', full_name='com.levven.protobuf.coldfire.spa_peak.PeakHeater', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakFilter', full_name='com.levven.protobuf.coldfire.spa_peak.PeakFilter', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PeakOzone', full_name='com.levven.protobuf.coldfire.spa_peak.PeakOzone', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakHeater', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakHeater', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakFilter', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakFilter', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MidPeakOzone', full_name='com.levven.protobuf.coldfire.spa_peak.MidPeakOzone', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Sat', full_name='com.levven.protobuf.coldfire.spa_peak.Sat', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Sun', full_name='com.levven.protobuf.coldfire.spa_peak.Sun', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Mon', full_name='com.levven.protobuf.coldfire.spa_peak.Mon', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Tue', full_name='com.levven.protobuf.coldfire.spa_peak.Tue', index=22,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Wed', full_name='com.levven.protobuf.coldfire.spa_peak.Wed', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Thu', full_name='com.levven.protobuf.coldfire.spa_peak.Thu', index=24,
      number=25, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Fri', full_name='com.levven.protobuf.coldfire.spa_peak.Fri', index=25,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=535,
)

DESCRIPTOR.message_types_by_name['spa_peak'] = _SPA_PEAK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_peak = _reflection.GeneratedProtocolMessageType('spa_peak', (_message.Message,), {
  'DESCRIPTOR' : _SPA_PEAK,
  '__module__' : 'SpaPeak_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.coldfire.spa_peak)
  })
_sym_db.RegisterMessage(spa_peak)


# @@protoc_insertion_point(module_scope)
