# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpaRouter.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpaRouter.proto',
  package='com.levven.protobuf.coldfire',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fSpaRouter.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xa4\x01\n\nspa_router\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12<\n\nencryption\x18\x03 \x01(\x0e\x32(.com.levven.protobuf.coldfire.ENCRYPTION\x12\x38\n\x08protocol\x18\x04 \x01(\x0e\x32&.com.levven.protobuf.coldfire.PROTOCOL*^\n\nENCRYPTION\x12\x13\n\x0f\x45NCRYPTION_NONE\x10\x00\x12\x12\n\x0e\x45NCRYPTION_WEP\x10\x01\x12\x12\n\x0e\x45NCRYPTION_WPA\x10\x02\x12\x13\n\x0f\x45NCRYPTION_WPA2\x10\x03*B\n\x08PROTOCOL\x12\x11\n\rPROTOCOL_NONE\x10\x00\x12\x10\n\x0cPROTOCOL_AES\x10\x01\x12\x11\n\rPROTOCOL_TKIP\x10\x02'
)

_ENCRYPTION = _descriptor.EnumDescriptor(
  name='ENCRYPTION',
  full_name='com.levven.protobuf.coldfire.ENCRYPTION',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WEP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WPA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCRYPTION_WPA2', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=216,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_ENCRYPTION)

ENCRYPTION = enum_type_wrapper.EnumTypeWrapper(_ENCRYPTION)
_PROTOCOL = _descriptor.EnumDescriptor(
  name='PROTOCOL',
  full_name='com.levven.protobuf.coldfire.PROTOCOL',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_AES', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_TKIP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=312,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

PROTOCOL = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
ENCRYPTION_NONE = 0
ENCRYPTION_WEP = 1
ENCRYPTION_WPA = 2
ENCRYPTION_WPA2 = 3
PROTOCOL_NONE = 0
PROTOCOL_AES = 1
PROTOCOL_TKIP = 2



_SPA_ROUTER = _descriptor.Descriptor(
  name='spa_router',
  full_name='com.levven.protobuf.coldfire.spa_router',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='com.levven.protobuf.coldfire.spa_router.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='com.levven.protobuf.coldfire.spa_router.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryption', full_name='com.levven.protobuf.coldfire.spa_router.encryption', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='com.levven.protobuf.coldfire.spa_router.protocol', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=214,
)

_SPA_ROUTER.fields_by_name['encryption'].enum_type = _ENCRYPTION
_SPA_ROUTER.fields_by_name['protocol'].enum_type = _PROTOCOL
DESCRIPTOR.message_types_by_name['spa_router'] = _SPA_ROUTER
DESCRIPTOR.enum_types_by_name['ENCRYPTION'] = _ENCRYPTION
DESCRIPTOR.enum_types_by_name['PROTOCOL'] = _PROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

spa_router = _reflection.GeneratedProtocolMessageType('spa_router', (_message.Message,), {
  'DESCRIPTOR' : _SPA_ROUTER,
  '__module__' : 'SpaRouter_pb2'
  # @@protoc_insertion_point(class_scope:com.levven.protobuf.coldfire.spa_router)
  })
_sym_db.RegisterMessage(spa_router)


# @@protoc_insertion_point(module_scope)
